# Author: Pascal Haupt
# Configuration for deploying Typebot with Podman or Docker Compose
# Includes PostgreSQL database, Redis cache, and Typebot builder/viewer services

services:
  typebot-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'listen_addresses=*'

  typebot-redis:
    image: redis:alpine
    restart: always
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
    volumes:
      - redis-data:/data
      - ./volumes/redis-data:/data

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
      - typebot-redis
    ports:
      - "8080:3000"
    env_file: .env
    environment:
      REDIS_URL: redis://typebot-redis:6379

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    depends_on:
      - typebot-db
      - typebot-redis
    ports:
      - "8081:3000"
    env_file: .env
    environment:
      REDIS_URL: redis://typebot-redis:6379

volumes:
  db-data:
  redis-data:
